// <auto-generated />
namespace DemoDoan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class version117 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version117));
        
        string IMigrationMetadata.Id
        {
            get { return "201911130153552_version1.1.7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
