// <auto-generated />
namespace DemoDoan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class version15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version15));
        
        string IMigrationMetadata.Id
        {
            get { return "201910140724280_version1.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
